# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "XVII Symposium of Mexican Studies and Students in the UK"
email: "symposiummx2019@gmail.com"
description: "Challenging ideas about Mexico and the World"
baseurl: "/"
url: "https://www.symposiummx.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-112761340-3"
googleAnalyticsSiteUrl: "www.symposiummx.com"
siteVerification: "Fl4V_9ef3aHWq0GpmVQFbZWem2e-anIHkPPoVoz6OT8"

# Organizer Info
organizerName: "Cambridge University Mexican Society (CUMEXSOC)"
organizerAlternateName: "Society of Mexican Students in the United Kingdom (MexSoc UK)"
organizerDescription: "Building today our Mexico for tomorrow."
organizerEmail: "symposiummx2019@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"

# Head
metaKeywords: "mexico, uk, research, cambridge"
twitterAccount: "@MX_Symposium"
socialImageSrcGooglePlus: "/img/seo/organizer-logo.png" # "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/organizer-logo.png" # "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/organizer-logo.png" # "/img/seo/sharing-facebook.png"

# Documents
# c4programme: "/assets/Programme_XVII_Symposium_MX.pdf"


# Navigation
navigationLinks:
  - {permalink: "/", text: "Home"}
  - {permalink: "/speakers/", text: "Speakers"}
  # - {permalink: "/schedule/", text: "Schedule"}
  - {permalink: "/art-exhibition/", text: "Art Exhibition"}
  # - {permalink: "/registration/", text: "Registration"}
  - {permalink: "/accommodation/", text: "Accommodation"}
  - {permalink: "/team/", text: "Team"}
  # - {permalink: "/blog/", text: "Blog"}

 # - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://www.eventbrite.com/e/xvii-symposium-of-mexican-studies-and-students-in-the-uk-tickets-58300972779#tickets", text: "Register"}
 - {link: "https://drive.google.com/file/d/1TKt2LXhr4x-GuMI_xLcmL_WrmNJMe1xP/view", text: "Programme"}
rightNavigationButtons:
 - {link: "https://www.eventbrite.com/e/xvii-symposium-of-mexican-studies-and-students-in-the-uk-tickets-58300972779#tickets", text: "Register"}
 - {link: "https://drive.google.com/file/d/1TKt2LXhr4x-GuMI_xLcmL_WrmNJMe1xP/view", text: "Programme"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "<typeout>"
eventDate: "26-28 June, 2019"
typeoutTextValues: '"SymposiumMX 2019","SymposiumMX"'
typeoutFallback: "SymposiumMX 2019"
heroButtons:
 - {link: "https://www.eventbrite.com/e/xvii-symposium-of-mexican-studies-and-students-in-the-uk-tickets-58300972779#tickets", text: "Register here"}
 - {link: "https://drive.google.com/file/d/1TKt2LXhr4x-GuMI_xLcmL_WrmNJMe1xP/view", text: "Programme"}

# About Block
aboutImage: "mexsocuk-logo.png"
aboutTitle: "<strong>XVII Symposium of Mexican Studies and Students in the UK</strong>"
aboutText: "<h5>Challenging ideas about Mexico and the World</h5>
<p align='left'>The Symposium of Mexican Students and Studies in the United Kingdom is an annual multidisciplinary meeting that provides a unique forum to present current academic work, engage in pertinent debates, and foster novel perspectives and collaborations.</p>
<p align='left'>Over the past sixteen years, the symposium has become the most relevant academic event in the United Kingdom for students, academics and practitioners interested in topics related to Mexico. This year's edition is co-hosted by the Cambridge University Mexican Society (CuMexSoc), at the University of Cambridge, and the  the Mexican Students Society in the United Kingdom (MexSocUK).</p>
<p align='left'>In broad terms, the scope of the symposium encompasses seven areas:</p>
<ul style='text-align:left'>
  <li>Physical Sciences (Mathematics, Physics, Chemistry, Astronomy)</li>
  <li>Biological Sciences (Medicine, Biology, Psychology, Genomics)</li>
  <li>Engineering and Technology (Materials, Construction, Aeronautics and Computer Science)</li>
  <li>Social Sciences (Education, Economics, Business and Management, Political Science, History, Law)</li>
  <li>Arts & Humanities (Art, Music, Literature, Architecture, Religion, Philosophy)</li>
  <li>Energy and Sustainability (Energy Transition, Ecology, Conservation, Climate Change)</li>
  <li>Mexican Studies (Security, Mexico's History, Politics, Law)</li>

</ul>
<p align='left'>During three days (26th - 28th June 2019), the symposium will offer a remarkable occasion to attend keynote presentations from outstanding leaders in relevant fields. At the same time, the symposium will offer a unique opportunity to actively participate and engage in academic paper presentations, lightning talk sessions, and poster sessions.</p>
<p align='left'>We very much look forward to welcoming you in Cambridge!</p>"
aboutInnovativeTitle: "<strong>Innovative Spaces</strong>"
aboutInnovativeText: "<p align='left'>‘Transforming ideas about Mexico and the World’ is absolutely delighted to be able to contribute to this annual Symposium by creating innovative spaces within this year’s academic programme.  These innovative spaces consist of:</p><p align='left'><ol style='text-align:left'><li><strong>Networking Sessions with Key Enterprises, Research Councils and Scientific Centers from Mexico and the UK.</strong></li><li><strong>An art exhibition curated especially for the Symposium that aims to promote contemporary arts from Mexico internationally.</strong></li></ol><p align='left'>Artists are invited to showcase their work at an art exhibition to be held at this year’s Symposium. The intention is to inspire ideas and open cultural dialogue through the rich language of Mexican art. Thematically, the exhibition aims to portray and contextualise the Symposium’s core theme, which is “Challenging ideas of Mexico and the world”. Various art forms are welcome, including paintings, drawings, photography and mixed media work, preferably in small scale formats. Artists are encouraged to submit a brief description of their proposed works, including specifications of size and medium, through the abstract submission procedure.</p><p align='left'>Submissions: Artists are invited to showcase their work at an art exhibition to be held at this year’s Symposium. The intention is to inspire ideas and open cultural dialogue through the rich language of Mexican art. Thematically, the exhibition aims to portray and contextualise the Symposium’s core theme, which is “Challenging ideas of Mexico and the world”. Various art forms are welcome, including paintings, drawings, photography and mixed media work, preferably in small scale formats. Artists are encouraged to submit a brief description of their proposed works, including specifications of size and medium, through the abstract submission procedure.</p>"
# aboutBlock:
 # - {title: "Conference", image: "conference.jpg", text: "Challenging ideas about Mexico and the World" }
 # - {title: "Social", image: "workshop.jpg", text: "Full-day of social activities!" }
 # - {title: "Social", image: "workshop.jpg", text: "Full-day of social activities!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Our Keynote Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
mapkey: ""
locationBlockTitle: "Location"
eventLocationName: "Mill Lane Lecture Rooms"
eventLocationLink: "https://www.cam.ac.uk/"
eventStreetAddress: "8 Mill Ln"
eventAddressLocality: "Cambridge"
eventAddressLocalityRegion: ""
eventPostalCode: "CB2 1RX"
eventAddressCountry: "UK"
eventStartTime: "2019-06-26T12:00"
eventDoorTime: "12:00"
eventEndTime: "2019-06-28T20:00"
eventPlaceCoordinates: "52.2016796, 0.1168942"
mapCenterCoordinates: "52.2016796, 0.1168942"
mapMobileCenterCoordinates: "52.2016796, 0.1168942"



# Venue Block
# venueBlockTitle: "Venue"
# venueBigImage: "venue_0.jpg"
# venueSmallImage1: "venue_1.jpg"
# venueSmallImage2: "venue_2.jpg"
# venueSmallImage3: "venue_3.jpg"
# venueTitle: "Kinopalace Cinema"
# venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "SymposiumMX2019"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=MX_Symposium", icon: "twitter"}
 - {link: "https://www.facebook.com/symposiummx2019/", icon: "facebook"}
 # - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.facebook.com/CUMexicanSociety/", text: "CUMexSoc"}
   # - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:symposiummx2019@gmail.com", text: "symposiummx2019@gmail.com"}
 # -
  # title: "FAQ"
  # links:
  #  - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: " "
aboutUs: "The Cambridge Organising Committee is composed mainly of Cambridge  Graduate Students and Mexicans living in Cambridge who share a diverse  disciplinary background and are committed to making a positive and  significant contribution to Mexico. If you have any questions or just want to chat with any of us, please feel free to get in touch!"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "52.2016796, 0.1168942"
logisticsMapMobileCenterCoordinates: "52.2016796, 0.1168942"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Cambridge"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Cambridge. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Cambridge.'}
 - {title: "Hotels", information: 'Cambridge has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
# aboutHackathonTitle: "Meet our themes"
# hackathonRows:
#  - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
#  - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
#  - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
# judgesImage: "judges.jpg"
# judgesTitle: "Judges"

# Hackathon Prizes Block
# prizesTitle: "Prizes"
# prizes:
#  - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
#  - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
#  - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
# hackathonLocationBlockTitle: "Location"
# hackathonLocationName: "Communa"
# hackathonLocationLink: "http://communa.net.ua/"
# hackathonStreetAddress: "1 Halytska St"
# hackathonAddressLocality: "Lviv"
# hackathonAddressLocalityRegion: "Lvivska"
# hackathonPostalCode: "79000"
# hackathonAddressCountry: "Ukraine"
# hackathonTimeTitle: "Hack through"
# hackathonStartTime: "2014-10-24T10:00"
# hackathonDoorTime: "09:00"
# hackathonEndTime: "2014-10-25T00:00"
# viewOnMap: "View on Google Maps"
# hackathonPlaceCoordinates: "52.2016796, 0.1168942"
# hackathonMapCenterCoordinates: "52.2016796, 0.1168942"
# hackathonMapMobileCenterCoordinates: "52.2016796, 0.1168942"
