version: '3'
services:
   website:
     build: .
     ports:
       - "4000:4000"
     volumes:
       - .:/srv/jekyll/
     # command: jekyll serve --watch --incremental
     # command: bundle exec jekyll serve  --watch --incremental --config _config.yml, _config_dev.yml
     command: bundle exec jekyll serve --drafts --livereload --host "0.0.0.0" --config _config.yml, _config_dev.yml

# jekyll:
#     image: jekyll/jekyll
#     command: jekyll serve --watch --incremental
#     ports:
#         - 4000:4000
#     volumes:
#         - .:/srv/jekyll
